# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b357b5c9a71b05a5368cb47e4753667285d2f2115f5d7ac7545b05ebd0e35959c69823c02de6b109273ad8a410616c2627a3c3a94cade4e1f26d2aa5b987d686

test:
  secret_key_base: fc90eea5d35697ae4c603f7215fd37dffcd3b28c86ff181a037507aae721a52f87ea44817857e262248e46340bd708b6519b63d95260d1c6d9de000ef9ebd58f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
